id: rhcs-bpms-install
title: Red Hat Cloud Suite - JBoss BPM Suite Install Demo
github_repo_url: https://github.com/redhatdemocentral/rhcs-bpms-install-demo
technologies:
  - Red Hat CDK
  - JBoss BPM Suite
  - OpenShift Enterprise  
summary: Project to automate the installation of JBoss BPM Suite using the Red Hat Container Development Kit (CDK) for application development activities on OpenShift.
level: Beginner
product: rhcs
author: Andrew Block, Eric D. Schabell
